name:                simple-parser
version:             0.6.1
github:              "ejconlon/simple-parser"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
category:            Parsing
synopsis:            Simple parser combinators

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/simple-parser#readme>

dependencies:
- base >= 4.12 && < 5
- containers >= 0.6 && < 0.7
# - errata >= 0.2 && < 0.3
- list-t >= 1.0 && < 1.1
- mmorph >= 1.1 && < 1.2
- mtl >= 2.2 && < 2.3
- nonempty-containers >= 0.3 && < 0.4
- scientific >= 0.3 && < 0.4
- text >= 1.2 && < 1.3
- text-builder >= 0.6 && < 0.7

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- KindSignatures
- MultiParamTypeClasses
- StandaloneDeriving
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  simple-parser-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-parser
    - tasty
    - tasty-hunit
    - tasty-th
