name:                simple-parser
version:             0.2.3
github:              "ejconlon/simple-parser"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
category:            Parsing
synopsis:            Simple parser combinators

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/simple-parser#readme>

dependencies:
- base >= 4.12 && < 5
- containers >= 0.6 && < 0.7
- list-t >= 1.0 && < 1.1
- mmorph >= 1.1 && < 1.2
- mtl >= 2.2 && < 2.3
- scientific >= 0.3 && < 0.4
- text >= 1.2 && < 1.3

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  simple-parser-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-parser
    - tasty
    - tasty-hunit
    - tasty-th
