name:                simple-parser
version:             0.1.0
github:              "ejconlon/simple-parser"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/simple-parser#readme>

dependencies:
- base >= 4.12 && < 5
- containers >= 0.6.2.1 && < 1
- exceptions >= 0.10.4 && < 1
- list-t >= 1.0.4 && < 2
- microlens >= 0.4.11.2 && < 1
- mtl >= 2.2.2 && < 3
- transformers >= 0.5.6.2 && < 1

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - Rank2Types
  - TypeApplications
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  simple-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-parser

tests:
  simple-parser-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-parser
    - tasty
    - tasty-hunit
